### ISSUE TITLE
Irish variants of e: tall e, ea ligature

### ISSUE THREAD

**Issue by silmeth** [psb1558/Junicode-font#180] opened 2023-06-02 20:37 UTC
More a loose idea that I think would fit the font than a true character request (cause I don’t really have a true need for this, at least now, myself). So feel free to close it if it doesn’t make sense or there’s no need to add them.

I don’t know how useful they’d be in general (and if they’re used outside of Irish mss. and early print at all) – but I haven’t really found modern fonts with those.

Old Irish manuscripts had a variant of ⟨e⟩ glyph called ‘tall e’ (see [*E (allograph)* in Tionscadal na Nod](https://codecs.vanhamel.nl/E_(allograph))).

And also a ligature *ea* composed of *e* and a subscript scribble for *a* (see [*ea (ligature)*](https://codecs.vanhamel.nl/Ea_(ligature))), similar to *ę*.

In later manuscripts and in print both of them stood for *ea* – and both were used in early Irish print – up to early 19th century.

### Modern fonts ###
Gaelchló has one font with those, specifically designed to typeset texts with old abbreviations, [*Seanchló na nod*](https://www.gaelchlo.com/snod.html) where the two are available under characters `<` and `=`:

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/3e3cbbff-d41d-442d-8c85-7ae44eca80f4)

Not sure if there are any other fonts.

### Old print ###

Some printed examples:
1618, *Scáthán Shacramuinte na hAithridhe*
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/47d51958-f818-4eed-b222-436e947fc5bd)
> ċoi*nn*siasa roimpe. D**ea**gla so dimth**ea**_cht_ ort ní as mó, déin an sgrúd…

1676, *Lucerna Fidelium*
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/81503a85-fb8b-4ed3-89ba-f93f4967d004)
> áta an t**ea**gasg criosduiḋe, ⁊ ciall ḟire na n*air*t**ea**gal a ta á nimr**éa**s **ea**ttorra fein, ⁊ lu*cht* a…

1681, *Tiomna Nuadh ar dtighearna agus ar slanuigheora Iósa Críosd*
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/7d2c2e65-48ed-4079-a377-4d2bd0369d96)
> 41. A*cht* ar mbeiṫ míċreidṁ**ea**ċ ḋóiḃ-sion fós tré ġáird**ea**ċas, agus ag d**éa**naṁ iongantais, a duḃ*air*t seision riú;

1728, *The Elements of the Irish Language*
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/d819cccf-3746-47a5-b196-83715144fe94)
> ainm, anf**ea**r. the man. gein, anḟir. of the man. (…) ainm. nafir. the men. gein, naḃf**ea**r. of the men.

(the second one here looks different… long s used fo *ea* or something?)

1818, *An Tiomna Nuadh*
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/1db01b78-b198-4552-b906-2210e91e6fce)
> ṡeanmóir ḋáoiḃ tar an [tsoisgéul] do ri*nn*eamar do ṡeanmóir ḋáoiḃ ċ**ea**na, bíoḋ sé mall*ui*ġṫe.

### Encoding ###
Since the two don’t have assigned Unicode codepoints (and I’ve no idea if they have been used in modern print at all, after early 19th c.), I don’t know how they should be encoded in the font.

I guess the *tall e* should just be a variant shape for *e* since that’s its original use (even if later comes to represent *ea* and is distinct from *e*), and the *ę*-like thing should be an optional ligature of *ea* (as that’s its origin).

**Comment by psb1558** [comment] 2023-06-02 23:11
This kind of thing interests me a lot. MUFI (and therefore Junicode) has a character described as "LATIN SMALL LETTER E TALL FORM": in Junicode it looks like this (I'll include a few other letters for context:
<img width="117" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/9779b3e0-d5f1-46b4-9a38-eb49c8892e89">
I made it an Old English word to make the point that what you're describing is common insular script. What we haven't done is include ligated forms--I suppose on the theory that there are so many ligatures in medieval manuscripts that we would drive ourselves crazy trying to include them all. I do that in my script fonts, though—for example my ancient Beowulf-1 font and my more recent Cerne font:
<img width="122" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/aa0eb6f7-229f-4872-af80-862e6384d1c2">
Those fonts are meant to produce the *style* of the original hand, and ligatures are a part of that style. Junicode can't hope to reproduce the style of medieval script—it's a roman font based on a 17th-c. model!

So I'm not eager to introduce new ligatures.

Now the e with "subscript scribble" is a different story. MUFI doesn't have anything like it, and its function is similar to, but not the same as, e caudata. I am open to adding something like this, but first I'd like to check whether e + U+1DD0 would do:
<img width="42" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/2d9729bf-da20-4e34-afe8-9fde9e5cdff7">
The mark below is actually from Visigothic script, but it looks a little like your e + scribble, doesn't it?

**Comment by silmeth** [comment] 2023-06-03 10:48
> I suppose on the theory that there are so many ligatures in medieval manuscripts that we would drive ourselves crazy trying to include them all. (…)
> 
> Junicode can't hope to reproduce the style of medieval script—it's a roman font based on a 17th-c. model!

That’s why all my examples are from 17th–19th century **print** and I didn’t write about all the scribal abbreviations. ;-)

It seems that when Irish started to be printed in the 17th c. a small set of abbreviations became “standard” and were included in most Irish typefaces. Charles Vallances listed them in his grammar of Irish from 1782:

![Irish abbreviations commonly used in printed books are these following: ⁊ ꝗ ꝗ(i) áo s̄ n̄ ui E ḃ ċ ḋ ġ ṁ ṗ ṡ ṫ](https://github.com/psb1558/Junicode-font/assets/5329644/783e25c8-076f-41a2-a07d-b8c65dd8320e)

Out of those I guess Junicode doesn’t have the ⟨ꝗ⟩ + ⟨i⟩ ligature for *air*, the *áo* and *ui* ligatures (but I didn’t mention them cause I wasn’t sure about the first one, and the latter two are just ligatures, not really completely independent characters).

Vallancey didn’t list the *ę*-like *ea* ligature – my guess is for him that was just a variant shape for the tall E.

Regarding the Junicode tall e – it seems to me that the Irish shape is always fully open, without a bowl (and in the early modern era it represents *ea*, not *e*).

Since all of them are *very common* in Irish print of the time (as long as Irish print at the time can be called common), I thought those might fit Junicode.

**Comment by psb1558** [comment] 2023-06-03 15:47
Thanks for the further explanation. I've also downloaded the Seanchlo na Nod GC font, from which I have learned some things, though it commits the considerable sin of encoding glyphs in non-standard places. I should mention that Junicode (and MUFI and Unicode) are very friendly to scribal abbreviations. Here are the glyphs that (it strikes me on first glance) might be included in (or already in) Junicode, with some preliminary thoughts:

- **tall open e**. If it sometimes represents e and sometimes ea, it ought to be in the font twice--once as a variant of e, and once as a pseudo-ligature of ea (included, perhaps, in the hlig feature). I'd like to see more images of the glyph in print and MS. Perhaps you could supply some links to good-quality images.
- **ar and air**. These look distressingly like variants of q, but I suppose there's nothing to do about that. Again, I'd like to see images from a variety of sources, especially early prints. It would be good to get a sense of the range of options. These would probably be in hlig, like the tall open e.
- The signs on the number sign and dollar sign in Seanchlo na Nod GC, am I right that these are variants of the Tironian sign? I have added anchors to U+204A so that marks can be placed on them.
- **ao**. See Junicode U+A735. This is treated as a letter, not a ligature, so marks, if added, are centered over the whole glyph, not over the individual elements. Is this all right, or does it need to be a ligature?

What are these characters, and are they worth including?
<img width="347" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/55864e8f-edf4-454a-9f1b-b777b06b626e">

**Comment by silmeth** [comment] 2023-06-03 19:06
1. I’ll try to link to some manuscripts later. I actually don’t have access to many good-quality scans of older Irish printed books, so I’m not sure what I can find – but will try to provide some later too.
2. **ar** and **air** – those are actually just *ꝗ* and a ligature *ꝗ* + *i* – Irish scribes used those for *que* in Latin and for *ar* in Irish. In Old Irish **ar** means ‘for, because of’ and it often translated Latin *quia*, thus the abbreviation for *quia* was adopted for the Irish syllable *ar*, see https://codecs.vanhamel.nl/Ar_(with_stroke), for **air** a superscript *i* was added, see: https://codecs.vanhamel.nl/Air_(symbol_with_superscript)
3. They are tironian ⁊ with the “fada” (acute accent marking length) and with punctum delens (which in later Irish became mark of lenition of a consonant, equivalent to *h* after the consonant). Since ⁊ stood for *et* (which in turn in OIr. was used for /ed/, later spelt *ed*) – ⁊́ is used for OIr. *-ét*, classical *-éad*; ⁊̇ stands for Old/Middle Irish *-eth*, classical *-eadh*, see the primer 4 (second page) there: https://leamhquiz.web.app/#/Public/Paleography (part of the [https://xn--lamh-bpa.org/](léamh.org) website).  ![⁊ – *et, agus, and*, sEis⁊̇ – *seiseadh*, ċoiṁ⁊́ – *choimhéad*](https://github.com/psb1558/Junicode-font/assets/5329644/8459f0ba-ac19-434f-a337-4d91208da6cd)
Those have also variants with spiritus asper – since it stood for *h*, it was often interchangeable with the dot: https://codecs.vanhamel.nl/Eth_(Tironian_et_with_spiritus_asper). There is an entry for ⁊́ in Tionscadal na Nod but they don’t have an image there: https://codecs.vanhamel.nl/%C3%89ad_(Tironian)
4. I think centering the diacritics over ꜵ (*ao*) for Irish is fine – the length mark in general was placed above **the syllable** – in the manuscripts it can be above any letter belonging to the long syllable, and in print it’s often seemingly random which vowel, if a few consecutive there are, gets it. As you can see in Vallancey’s list the acute is also kinda above the centre of the *ao* character. (also *ao* was always long, so depending on the scribe’s/typesetter’s preference it either got the length mark or not, in modern Irish it’s always *ao* without length mark).
5. Those 6 characters are, in order: *na* (https://codecs.vanhamel.nl/Na_(digraph)), ligature *rr* (https://codecs.vanhamel.nl/Rr_(ligature)), *go/gur* (not sure if that one’s in Tionscadal na nod, perhaps this entry with no image: https://codecs.vanhamel.nl/G_with_superscript_o), ??? (no idea what the inversed P under ⟨¶⟩ is, maybe actually just a glyph for ¶?), and the last two, I think, are the same: Latin Tironian *con* – also used in Irish for *con* (https://codecs.vanhamel.nl/Con_(reversed_c)) (just upper and lowercase? if not, not sure what the bigger one is).

You can see the *rr* ligature in print in one of the examples I posted earlier:
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/c369f78d-4e3d-46c9-abce-1f2658f3e093)
> eattorra

the use of most of those characters is explained in Irish there under the header *Noda na láṁscríḃinní* (‘manuscript abbreviations’) – I think Google Translate should be able to handle this page: https://www.gaelchlo.com/peann.html

**Comment by silmeth** [comment] 2023-06-03 19:19
Also, the *sed* abbreviation (s᷃, s with suspension stroke, https://codecs.vanhamel.nl/S_(insular)_with_suspension_stroke) is used in Irish (including print, see Vallancey’s list above) for either *acht* or just *cht* (also spelt *achd, -chd*) – that’s again through translation from Latin, early Irish *acht* means ‘but’ (modern *ach*), so s᷃ became to mean the sequences *acht* and *cht*.

**Comment by psb1558** [comment] 2023-06-03 20:06
Okay, this is very useful. For q with diagonal stroke, Junicode has U+A759, and you can put a combining i (U+0365) over it:
<img width="29" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/caa1a529-0f94-42cd-896c-0bb1d8f3357f">
There's also a dotless version of the combining i, which you can find in the Junicode documentation.

For sed, you can place a macron (U+0304) over a combining insular s:
<img width="21" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/47e9004d-5c58-40ff-b25e-3ee78f120895">
Or use a tilde, if you prefer (U+0303).

For a rough breathing, the standard Unicode is U+0314:
<img width="24" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/dbd1da2b-250d-43be-83b6-c632c3a465e1">
But that's for Greek, I guess: anyway, it doesn't look like the spiritus asper characters on the page you link. I could create a variant of U+0314, if you think it worthwhile. Or you could use another mark that looks right—Junicode has lots of them.

That just leaves the high e that should definitely be added, and I think I've got enough images of that now—though if you know of variant shapes, I'd like to see those.

**Comment by silmeth** [comment] 2023-06-03 20:45
Regarding the spiritus asper – as I understand it, it was taken from the Greek, but in Irish the shape kind-of evolved and sometimes it was reversed:
![ch](https://github.com/psb1558/Junicode-font/assets/5329644/9e28696b-97b8-49f8-8bfd-44775dfa390e)
as if with smooth breathing sign.

Sometimes it has the ‘half-(H)eta’ shape (I guess inspired by this shape: https://commons.wikimedia.org/wiki/File:Heta_uc_lc.svg?):
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/d2f6a284-64f9-486b-8cdd-1f23a7778f7c)

which sometimes becomes kinda *v*-shaped:
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/927c0040-86cb-4655-9389-8044197ec8d4)

I’ve no idea how common the tilde-like shape from Tionscadal na Nod image was (I’m no expert on Irish manuscripts; I just learn Classical Gaelic and Old Irish and *sometimes* look at them, so there’s **lots** I’ve no idea about there!).

**Comment by psb1558** [comment] 2023-06-03 22:20
For the comma-shape, you could use U+0313:
<img width="24" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/7b5bdb88-1dcc-4b25-b61f-889ea87bd76f">
The other rough breathing mark reminds me a little of U+1DD1:
<img width="29" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/da0505cd-2da7-4dda-ad69-bfdbbeafa7eb">
But probably this is not close enough (it's actually a stylized r-rotunda). I think I ought to make a new one.

**Comment by silmeth** [comment] 2023-06-03 23:17
Some more examples of the spiritus asper – some more like heta Ͱ, a few a bit more *v*-like, all by one hand, from Middle Irish, 12th c., Book of Leinster, [Trinity College, MS 1339, p. 113](https://www.isos.dias.ie/TCD/TCD_MS_1339.html#113):

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/fa5828e9-5e84-44f4-bd37-9d67732ba8c4)

And one more, a bit later: 15th c., *An Leabhar Breac*, [RIA MS 23 P 16, p. 5](https://www.isos.dias.ie/RIA/RIA_MS_23_P_16.html#9):
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/99ca2750-402e-440a-917b-08c5ad8cdef6)

**Comment by psb1558** [comment] 2023-06-03 23:39
Is this one of the high e's that are transcribed ea?
<img width="150" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/8402a0ef-dd90-4c14-8218-7a592097823a">

**Comment by silmeth** [comment] 2023-06-04 00:20
It’s exactly this character – but earlier stage of the language, and here it stands just for *e*, *ferge* (normalized and also later spelling *feirge*).

Search for *ferge fo chích curad* there to get the transcription of this part of the ms.: https://celt.ucc.ie/published/G301016.html

**Comment by psb1558** [comment] 2023-06-04 01:29
Here's the first character, spiritus asper:
<img width="57" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/889e8d12-8846-4daf-a7cd-7565f328414c">
It's based on the one in the Book of Uí Mhaine, which I think quite attractive. I can't make it a variant of the Greek diacritic--I'm out of Character Variant features. Instead, it's one of many variants of combining macron (U+0304). Apply feature cv84[36] or use tags: U+0304 + &__3; + &__6; and apply feature ss10.

It has no encoding.

**Comment by silmeth** [comment] 2023-06-05 10:47
17th century ms., a famous Classical Gaelic grammatical tract, a few examples of “tall e” and a few more things, [RIA MS 24 P 8, p. 5](https://www.isos.dias.ie/RIA/RIA_MS_24_P_8.html#7):
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/47f4e759-d780-4bba-ae1b-1d3c85b55865)

words with highlighted parts:
*Aib**gh**it**ea**r* (spiritus asper and tall e)
*t**ēacht**a* (*ę*-like *ea* and *cht* – no idea why the *e* has double ogonek/scribble for *a*, it’s missing length mark)
*athaithmh**ea**ch* (tall e)
***áo**sa* (*ao* ligature)
*cédughd**ar*** (*ar*)
*C**ea**s* (tall e)
*aibghi**tear*** (vertical tilde for *ear*, see https://codecs.vanhamel.nl/Er_(vertical_tilde))
*ní hannsa* (‘not difficult’, *.īn̄.* used as abbreviation)

Another 17th (or 18th?) c. ms. with poetry, different style, [RIA MS 23 M 29, p. 301](https://www.isos.dias.ie/RIA/RIA_MS_23_M_29.html#5):
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/ed46929e-0bfe-41ad-bd91-7920f1b5458c)
*mh**éad*** (⁊́ for *éad*)
***ar***
*b**liadh**uin* (*l* with suspension stroke and punctum delens as abbreviation for *l* + something lenited, here *-liadh-*)
*d**éa**g* (*ę*-like *ea*, length mark seems missing)
*i**na*** (ligature *n* + the *a* scribble)
*dhead(h?)fhlaith* (the ⁊ + punctum delens, but I see an edition of this poem transcribing this as *dhedfhlaith*)

**Comment by psb1558** [comment] 2023-06-05 12:56
Here's a go at tall open e (several words you used above to illustrate):
<img width="693" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/53a1c42f-3850-4b38-925a-79129b7d51fd">
Settings used to produce this:
- Script/language: latn/IRT (Traditional Irish)
- ss02 (Insular letter-forms)
- cv84[36] (variant of macron: spiritus asper)
- cv10[5] (variant of e: tall open e)

Where practical, I have kerned it very tight with the following letter:
<img width="597" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/e0342359-853c-4c09-aae3-b0c6522e524c">
Comment?

**Comment by silmeth** [comment] 2023-06-05 13:08
IMO looks very nice!

Thinking about it, IMO semantically it would make more sense to put Irish spiritus asper as a variant of the dot above (even though its main purpose is derivative in mathematics) – it’s a form of lenition dot in later mss. after all; or as a form of modifier h maybe?

Macron IMO is problematic because it often is used in ms. editions with different meaning: to provide length mark missing in the ms. (like above in *tēachta* the *ē* means that the vowel is long even though not marked so in the ms.).

nitpick about example word used: *nairteagal* should have the ꝗ with superscript *i*, not acute (it’s *air*, not *ár*) (actually, semantically it’s typically edited as *n-airteagal*)

**Comment by psb1558** [comment] 2023-06-05 13:23
Can't do the spiritus asper as variant of dot accent: I'm (unfortunately) out of character variant features! For better or worse, I chose macron as the base for *all* variant marks on cv84. One has got to turn the feature on and off if a text uses both macron and variants of macron. It's the same with cv10: regular e and tall open e will often have to coexist in the same text—sometimes in the same word. Best way to handle this is word processor styles, CSS classes, LaTeX custom commands.

Sorry about my errors of transcription: I don't know a word of Irish!

**Comment by silmeth** [comment] 2023-06-05 13:34
Yes, I understand you need to switch the features mid-text to use variant forms, I just hoped the spiritus could be used as a variant of something else just for the semantics of the base underlying text (searchability, text indexing, etc.) – cause spiritus asper and macron do have different meanings (while the dot and spiritus asper mean the same thing in a way, in later mss. they’re just variant forms).

But macron is better than nothing! I guess that’s an OK solution if other can’t be used due to OpenType limitations.

**Comment by silmeth** [comment] 2023-06-05 14:25
One more comment: the upper stroke of the tall end extends rightward noticeably more than the lower stroke – generally both in the manuscripts and in the old printed examples.

I’m no font designer and don’t know if it makes sense for Junicode, but I *think* it might look better here too if the upper part extended a bit more to the right.

**Comment by silmeth** [comment] 2023-06-05 17:00
Examples from another 17th c. ms. (with fragments of the same grammatical tract) [NLS Adv. 72.2.2, f. 37r](https://www.isos.dias.ie/NLS/NLS_Adv_MS_72_2_2.html#76) – these have straight vertical stroke in the lower part, extending right only in the upper part:

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/b70772e1-aea6-43b5-b11c-cf84ece8e581)
*substainnt**ea**cha ⁊ **ar***  (tall e followed by ċ, then *ar*)

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/c5cc6839-3075-41ce-a362-61d40e6646df)
*t-**ea**ntuillreim*

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/5607fe14-48f5-4de7-8a5c-73326222683b)
*o mb**ea**ntur* (tall e, also superscript *u* over *t* for *-ur*)

**Comment by psb1558** [comment] 2023-06-05 17:30
Thanks for the extra examples. If I could make up my own OpenType feature tags, then life would be so much easier. But I can't, and since Junicode is stuffed with features, I've got to do a fair amount of compromising.

The shape of tall open e is an interesting problem. At first the bottom curve extended farther to the right, but I reduced it by about a third to be more faithful to the models. This letter has got to be a compromise between early forms (both Irish and English), in which it is obviously just a variant of e, and later ones, where it has evolved so much that it has lost much of its resemblance to standard e.

For many characters, my test has been: *will this be intelligible to  all readers in the various contexts where it appears?* If I can find a shape that makes the answer to that question "yes," then that's what I go with. If I can't find such a shape, then variants are needed (an example of this is the Tironian sign, which has three different shapes in Junicode).

For this character, there seems a world of difference between these shapes:
<img width="47" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/9de129f1-657d-457f-a257-6f7adcb3eb76">  <img width="80" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/32a2a123-c753-40a6-bab8-34423cd9dde9">
One with a pretty tight, nearly closed loop, and the other looking more like an f or a long s than an e. So my very serious question (which I can't answer myself, because, as I said, I have never worked with Irish) is whether the present shape of tall open e (perhaps with a slightly wider top loop) will be intelligible to Irish scholars working with texts from all periods.

**Comment by psb1558** [comment] 2023-06-05 18:43
With respect to your more recent posts, I think Junicode can already handle most or all of this stuff. A possible exception is the attached subscript a, which I see now is related to the mark (U+1DD0) that I mentioned above. Interestingly, one very much like this 17th-c. form
<img width="69" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/6e90d140-40f3-43a5-8ca8-a79e5ab7860d">
is also found in the 9th/10th-c. English Parker Chronicle. I never knew that it wasn't a one-off form. Perhaps Junicode should have a combining mark for this.

**Comment by psb1558** [comment] 2023-06-05 18:45
The upper loop ought to come down farther, too, almost touching the x-height. I'll see what I can do.

**Comment by psb1558** [comment] 2023-06-05 19:17
Like this (I include the r because the e looks better with context.
<img width="48" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/422c18ff-d016-4f74-bbab-0953e8f239d6">

**Comment by psb1558** [comment] 2023-06-05 20:13
I have also added an entity for the spiritus asper. For the way entities work, see the Junicode Manual, section 4.10.3. This one is `&_sa;`

**Comment by silmeth** [comment] 2023-06-05 20:21
> With respect to your more recent posts, I think Junicode can already handle most or all of this stuff.

Yes, I think so, Junicode already handles most of the common things. The main missing pieces for Irish, IMO, were the two *ea* characters (open tall e, *ea*-thingy) and spiritus asper (especially since those are also among the common printed stuff).

Regarding *na*, note that *Seanchló na Nod*, for whatever reason, also included it:
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/f5528436-36a3-41dd-bdb0-05eb8129bcac)

I don’t think I’ve seen it in printed texts, but I guess it must have been common enough in manuscripts at least.

Interesting that for *na* Tionscadal na Nod gives different form (open, https://codecs.vanhamel.nl/A_(subscript_open)) of subscript a than for *ea* (https://codecs.vanhamel.nl/A_(subscript)). I’m not entirely sure if they’re really two different forms.

> Like this (I include the r because the e looks better with context. <img alt="image" width="48" src="https://user-images.githubusercontent.com/16215767/243451700-422c18ff-d016-4f74-bbab-0953e8f239d6.png">

That looks very good in my opinion!

**Comment by silmeth** [comment] 2023-06-05 20:28
For the subscript *a* – seems the open and non-open variants were just stylistic choice. Here a hand that uses the “open” one everywhere, [Book of Fermoy, p. 162](https://www.isos.dias.ie/RIA/RIA_MS_23_E_29.html#166):

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/2483df51-d8ae-4b0f-9510-1a5f4ae79ca5)
*fear **na** slei[gh]e* (*d(h)* for *gh* in ms., it seems)

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/d7ac3948-1bb7-428c-a19d-94da4faa8177)
*s**ua**s co teag[h] **na** trocaire*

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/a0a428ff-96e9-4570-b6c5-f737b5319277)
*l**ea**t isin [c]cat[h]raigh*

the same “open *a*” after *n*, *u** and *e* (and also two example of tall e – with different shapes! in *fear* and *teag[h]* respectively)

**Comment by silmeth** [comment] 2023-06-05 20:41
Some examples of less ornamental, more heta-like spiritus asper, [MS B ii 2, f. 1v](https://www.isos.dias.ie/RIA/RIA_MS_B_ii_2.html#6):

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/3a086d51-c0ed-4e0d-baff-a7f64172888e)
*breadh*

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/e7d778da-053a-4379-9cc9-de06a57b4d90)
*teamhair*

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/7aecf14c-2e2f-47b3-b0c7-ff4eeb6a290e)
*cid ōn cid*

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/4592b220-e622-4b70-9fef-4702b52bb662)
*liath mac lughna*

**Comment by psb1558** [comment] 2023-06-06 22:04
Aaaand italic:
<img width="74" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/61c3be35-3290-402f-9a0e-ed8aa0255f76">
Fonts with this new stuff, plus some other additions and fixes, will be posted, probably, by this weekend.

**Comment by psb1558** [comment] 2023-06-09 15:59
These new things are in version 1.059, now in the repository. Download and try it out--report any problems.

**Comment by silmeth** [comment] 2023-06-11 20:21
Started playing with it today. Looks nice!

One thing I noticed is that the glyphs for `cv84[36, 37]` in the manual are wrong (it’s 35 copy-pasted):
![](https://github.com/psb1558/Junicode-font/assets/5329644/d73806c9-543b-4e18-9375-28a7b327be9a)

Another thing (not directly related to these new features)  is that, at least in LibreOffice (haven’t played with XeLaTeX and web + browsers yet), `g` + combining macron with `ss02` and Irish language set turns to the default `g` glyph instead of the insular one (but separating the macron with grapheme joiner helps)
![](https://github.com/psb1558/Junicode-font/assets/5329644/7a0d821a-c16b-4815-9070-b8335fc05571)

Beside that, got the first few sentences from the grammatical tract transcribed:
![](https://github.com/psb1558/Junicode-font/assets/5329644/4d7c2761-8d16-4349-b652-cd44c8646c66)

tall e + insular d get their strokes very close to each other, almost touching

**Comment by silmeth** [comment] 2023-06-11 21:01
I see I made the error of applying the features only to the relevant character, which caused the kerning to be off.

With the feature applied to the following letter too it looks much better – but now *eċ* is a bit illegible cause the stroke of *e* almost touches the dot:
![](https://github.com/psb1558/Junicode-font/assets/5329644/71c4f46e-0304-41e0-a78d-1214d3058c74)

**Comment by psb1558** [comment] 2023-06-11 22:58
c and insular d with dot are precomposed characters in Junicode, so they can be kerned separately--thus the fix was easy. Tall open e with dotted d will look odd, though, since it's not a natural combination:
<img width="65" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/ef36ee33-67d4-41d6-92a2-a8ee211d2caf">
Do you have either a manuscript or early printed version of that combo that I could look at?

When you're doing a complex piece of typesetting, with lots of combining marks, it's worthwhile knowing something about how that layout engine works. **Before** any of the font's own programming gets applied, the layout engine **normalizes** the underlying text--that is, it substitutes precomposed characters that are present in the font for base + combining mark sequences. So when it comes to g + combining macron (U+0304), it substitutes gmacron (U+1E21), with the result that ss02, which substitutes insular b for roman g (but not gmacron), never gets executed for that character.

The **combining grapheme joiner** (U+034F) is included in Unicode specifically for this situation. Just place it between the base and the (first) combining mark, and it will defeat normalization for that combo, and all will be well.

In your sample, this doesn't look great:
<img width="51" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/53c82af3-2b4c-4f2f-b330-9a3d1f074224">
What character are you using for the overline? I can try to kern it so it's more centered. For the dots used as delimiters, I don't know what you're using, but I think periodcentered (U+00B7) would look a good bit better.

**Comment by silmeth** [comment] 2023-06-12 09:56
> Do you have either a manuscript or early printed version of that combo that I could look at?

I’ll give some examples of both *eċ* and *eḋ*:

from above:
![](https://user-images.githubusercontent.com/5329644/243419700-b70772e1-aea6-43b5-b11c-cf84ece8e581.png)
*substainnt**each**a* (the stroke of tall e above the dot, practically touching it)

from the main grammatical tract ms.:
![](https://github.com/psb1558/Junicode-font/assets/5329644/db3360af-c8e6-4f05-938e-be22da5ab2cb)
*a thaithmh**each***

![](https://github.com/psb1558/Junicode-font/assets/5329644/605fa0b4-bded-43a1-95f9-36d7a0dff97f)
*ro céadchumhdaigh**eadh***

[Coláiste na Rinne, LS 6, p. 12](https://www.isos.dias.ie/CNR/CNR_LS_6.html#12), *Cúirt an Mheadhón Oidhche*:
![](https://github.com/psb1558/Junicode-font/assets/5329644/10901407-3cb6-4b14-aaaa-a372c3d1f9df)
*bháins**each***

Some print, also with dotted *m*, cause I can’t find many examples quickly:
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/1c4f3873-95e5-4f40-bf18-295e29bd43b1)
*go headhmh**eadh**onach*

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/bfe06bba-0034-4513-8c98-0e4e0e5346e5)
*c**eadh**na*

![](https://github.com/psb1558/Junicode-font/assets/5329644/94446330-25dd-44c0-8afd-e1d06cbdeead)
*síoráir**eamh***

> When you're doing a complex piece of typesetting, with lots of combining marks, it's worthwhile knowing something about how the layout engine works. (…) So when it comes to g + combining macron (U+0304), it substitutes gmacron (U+1E21), with the result that ss02, which substitutes insular b for roman g (but not gmacron), never gets executed for that character.

Yes. I am aware of that. I pointed it out in case it’s a bug in the font – `ss02` does change the ġ character (u+0121) to the insular shape so I thought it might be worth pointing this doesn’t happen with other diacritics.

Of course g with macron isn’t something that exists in Irish, so it’s not needed the same way ġ is. So I also understand if ḡ is left in its non-insular shape deliberately.

> In your sample, this doesn't look great: ![](https://user-images.githubusercontent.com/16215767/244975747-53c82af3-2b4c-4f2f-b330-9a3d1f074224.png) What character are you using for the overline?

*i͞n*, ie. ⟨i⟩ + ⟨◌͞◌⟩ (u+035e, double macron) + ⟨n⟩

> For the dots used as delimiters, I don't know what you're using, but I think periodcentered (U+00B7) would look a good bit better.

Yeah, I was just playing around with character variants here and used regular “period” dot ⟨.⟩ with `cv70[1]`, I recon ⟨·⟩ would actually look better here (though those abbreviations are typically transcribed with the regular period: ⟨.i.⟩ ‘id est; eadhon’, ⟨.i͞n. ~ .n͞i.⟩ ‘ní hannsa’, ⟨.c.⟩ ‘cóir’, etc.).

**Comment by silmeth** [comment] 2023-06-12 10:20
Some examples from [*Aibidil Gaoidheilge ⁊ caiticiosma*](https://digitalcollections.tcd.ie/concern/works/qz20sz670?locale=en), which was printed in 16th c. in more antiqua-style typeface, more Junicode-like I guess – so might be of interest.

![](https://github.com/psb1558/Junicode-font/assets/5329644/3d4d56b1-6066-4af7-bdaf-5c60d73df58b)
*gídheadh cuirthear anionad* (tall *e* + ď, ligature *ui*)

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/4d35223c-0b10-4456-b11b-b2656daa9dd3)
*na neithi do geibhthear* (*na*, *ei*, tall *e*, *r* rotunda)

![](https://github.com/psb1558/Junicode-font/assets/5329644/bb34d381-f260-42a2-9f01-609142c45aab)
*dáois an Tighearna* (*ao*, tall *e*, *na*)

![](https://github.com/psb1558/Junicode-font/assets/5329644/4ccaab7e-86d0-4eb5-b7e5-6bc91d6976f0)
*a ⁊ o ⁊ u na trí ghuthaoighe leathna*

**Comment by silmeth** [comment] 2023-06-12 10:55
Also less macron-like more wavy suspension stroke
![](https://github.com/psb1558/Junicode-font/assets/5329644/ebf79326-76a7-461b-a941-1301047c9349)
*rinneadar do lucht*

**Comment by psb1558** [comment] 2023-06-12 11:15
So tall e and insular d get sort of tangled up together. That's fine (more or less) for the plain d, where a little kerning will do it:
<img width="191" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/bcca2965-82de-42b2-aa72-20a02e75edf3">
But the dotted d requires special treatment (this will work in the next build):
<img width="189" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/1d53f4a7-b496-4747-97c5-c7cfbf14ac46">
The wavy macron is `U+0304 + cv84[2]`:
<img width="48" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/892970e6-5144-40fb-bbb0-43ad7a20c51a">
Here the underlying sequence is **e + U+034F + U+0304 + d** with `lang=IRI + ss02 + cv10[5] + cv84[2]`. (You'll need U+034F most of the time to see any sort of variant of macron.)

**Comment by psb1558** [comment] 2023-06-12 11:26
I included dotted forms iof various insular letters for Irish a number of versions ago: those save users the bother of using U+034F. For more exotic base + mark combinations you still need U+034F.

**Closed** 2023-08-04 19:17 UTC
