### ISSUE TITLE
Position of double combining critical marks over digits

### ISSUE THREAD

**Issue by RDHWalker** [psb1558/Junicode-font#257] opened 2023-11-25 18:43 UTC
Please could the full-height digits 0 to 9 be added to the set of "tall characters" which cause the double combining critical marks to be positioned higher. This affects:

combining double breve (U+035D)
combining double macron (U+035E)
combining double tilde (U+0360)
combining double inverted breve (U+0361)
combining double circumflex above (U+1DCD)

One application for the combining double inverted breve (U+0361) above two digits is in the notation of fingering of keyboard instruments.

**Comment by psb1558** [comment] 2023-11-26 13:15
I have added all the lining digits to the relevant class. I must say, I am endlessly fascinated by the variety of uses to which my "font for medievalists" gets put!

**Comment by psb1558** [comment] 2023-12-02 21:32
I thought it was working, but it seems not to be. I'll post here again when I've got it going.

**Comment by psb1558** [comment] 2023-12-03 04:01
Actually, this is working everywhere I've tested but in LibreOffice. If the cause  of that failure is what I think it is, there's nothing I can do about it, so I'll close this now.

**Closed by psb1558** 2023-12-03 04:01 UTC
